### ISSUE TITLE
Provide coverage tests to check if all paths of the program are tested

### ISSUE THREAD

**Issue by rrahn** [seqan/app-template#30]
@rrahn commented on [Thu Mar 26 2020](https://github.com/seqan/product_backlog/issues/11)

### Description

The coverage tests should cover if possible the CLI tests. How can this be done if the CLI tests are called via a system call?

### Acceptance Criteria

- [ ] 

### Tasks

- [ ] Workout a prototype for solving this.

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

---

@marehr commented on [Mon Apr 20 2020](https://github.com/seqan/product_backlog/issues/11#issuecomment-616437714)

20.04.2020 Core-Meeting Resolution: In Iteration 27.04.2020 we prototype how to do this.
